### ISSUE TITLE
Code review Weasel Plants

### ISSUE THREAD

**Issue by Trey2k** [WeaselRP/weasel-plants#1]
This script needs to be reviewed

**Comment by verzano** [comment]
Is there a set of guidelines on naming functions, camel vs pascal case or so?

**Comment by Trey2k** [comment]
> Is there a set of guidelines on naming functions, camel vs pascal case or so?

I prefer Camel, but I have been bad about sticking with that I think. I don't think there is a official slandered

**Comment by Trey2k** [comment]
I think the main issue right now is how I am handling indexing. I need to make sure index does not change after removing a plant and have the same index server and client side. Currently it gets buggy when harvesting

**Comment by MrNewb** [comment]
Could you add a sql file?

**Comment by Trey2k** [comment]
> Could you add a sql file?

One has been added
